import "pkg:/source/view/debug/DeveloperScreen.bs"

namespace main
  @node("DeveloperScreen", "mv_DeveloperScreen")
  class DeveloperScreen extends mv.debug.DeveloperScreen

    protected override function createMenuPages() as mc.types.array
      return [
        m.getDefaultPage()
        m.getPage2()
        m.getPage3()
        m.getPage4()
      ]
    end function


    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    '++ Pages
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    protected function getPage2()
      return [
        ["List Editing (team screen)", function(): m.showScreen(m.createSGNode("TeamScreen")): end function]
        ["Grid Item JumpToItem", function(): m.showScreen(m.createSGNode("FocusOnGridItemScreen")): end function]
        ["Grid Item Moving", function(): m.showScreen(m.createSGNode("UpdateGridItemsScreen")): end function]
        ["List Updates", function(): m.showScreen(m.createSGNode("UpdateListDataScreen")): end function]
        ["Buttons", function(): m.showScreen(m.createSGNode("ButtonScreen")): end function]
        ["ControlGroup", function(): m.showScreen(m.createSGNode("ControlGroupScreen")): end function]
        ["TextInput", function(): m.showScreen(m.createSGNode("TextInputScreen")): end function]
        ["Task Runner", function(): m.showScreen(m.createSGNode("TaskRunnerScreen")): end function]

        ["Timer", function(): m.showScreen(m.createSGNode("TimerScreen")): end function]
      ]
    end function

    protected function getPage3()
      return [
        ["GridRow bug", function(): m.showScreen(m.createSGNode("ModuleScreen")): end function]
        ["Notification Screen", function(): m.showScreen(m.createSGNode("NotificationScreen")): end function]
        ["NavController", function(): m.showScreen(m.createSGNode("NavControllerTestScreen")): end function]
        ["Tab Controller", function(): m.showScreen(m.createSGNode("TabControllerTestScreen")): end function]
        ["Dynamic Container", function(): m.showScreen(m.createSGNode("DynamicContainerTestScreen")): end function]
        ["Animations", function(): m.showScreen(m.createSGNode("AnimationScreen")): end function]
        ["Advanced Animations", function(): m.showScreen(m.createSGNode("AdvancedAnimationExampleScreen")): end function]
      ]
    end function
    protected function getPage4()
      return [
        ["List OnEnterOnExit", function(): m.showScreen(m.createSGNode("ListEnterExitScreen")): end function]
      ]
    end function

  end class
end namespace
