import "pkg:/source/roku_modules/log/LogMixin.brs"
import "pkg:/source/core/MIOC.bs"
import "pkg:/source/core/Tasks.bs"
import "pkg:/source/core/Utils.bs"
import "pkg:/components/view/mixin/FocusMixin.bs"
import "pkg:/source/view/Animation.bs"
import "pkg:/source/view/NodeClass.bs"

namespace mc.sample

  @node("MainScene", "Scene")
  class MainScene extends mv.NodeClass
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    '++ Debug Fields
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    public _rLog as roSGNode
    public _appController as roSGNode
    public _global as roSGNode

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    '++ Views
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    private loadingBackgroundGroup as roSGNodeGroup
    private loadingBackground as roSGNode
    private loadingPosterGroup as roSGNodeGroup
    private loadingIndicator as roSGNode
    private loadingPoster as roSGNode
    private developerScreen as roSGNode

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    '++ Private Fields
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    protected log as rLog.Logger
    private args = {}
    private launchSequence as roSGNode
    protected top as dynamic

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    '++ Initialize
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    function new()
      super("MainScene")
      m.createSGNode("TrackerTask")
      m.configureLogger()
      m.createView()
    end function

    private function createView()
      m.loadingBackgroundGroup = m.createSGNode("mv_Group", m.top, "loadingBackgroundGroup")
      m.loadingBackground = m.createSGNode("mv_Rectangle", m.loadingBackgroundGroup, "loadingBackground", {
        color: "#000000"
        width: 1920
        height: 1080
      })
      m.loadingPosterGroup = m.createSGNode("mv_Group", m.top, "loadingPosterGroup")
      m.loadingPoster = m.createSGNode("mv_Poster", m.loadingPoster, "loadingPoster", {
        uri: "pkg:/images/app/nba-tv-logo-and-text-medium-$$RES$$.png"
        loadSync: true
        width: 1920
        height: 1080
      })
      m.loadingIndicator = m.createSGNode("LoadingIndicator", m.top, "loadingIndicator", {
        "width": 1920
        "height": 1080
        "backgroundVisible": false
        "text": ""
        "translation": [0, 0]
      })
    end function

    function getNode(node as roSGNodeRowList)
    end function
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    '++ Log
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    private function configureLogger()
      logger = rLog.initializeLogManager(["log_PrintTransport"], 5)
      m.log = new rlog.Logger("MainScene")
      m.log.info("Configuring log")
      logger.includeFilters = {
        ' "mv_TabController": true
        ' "mv_SimpleTransition": true
        ' "ButtonScreen": true
      }
      logger.excludeFilters = {
        "__ml_FocusIndicatorManager": true
        "FocusIndicatorManager": true
      }
      'bs:disable-next-line
      a = {
        "ml_List": true
        "ml_BaseRow": true
        "ml_BaseCell": true
        "ml_RowHeader": true
        "ml_GridRow": true
        "ml_HorizontalRow": true
        "ItemViewManager": true
        "ListItemViewManager": true
        "RowItemViewManager": true
        "GridRowItemViewManager": true
        "ItemScroller": true
        "RowItemScroller": true
        "GridItemScroller": true
        "ListItemScroller": true
        "ItemFocusManager": true
      }
    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    '++ Public Methods
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    ' This is called when all initial data is loaded. The app would show a loading spinner and loading background until this point
    function begin(args = invalid as object)
      m.log.info("begin")
      m.args = args
      m.top._global = m.global
      m.startLaunchSequence()
    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    '++ Private Methods
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    private function startLaunchSequence()
      m.log.info("starting launch sequence")
      m.launchSequence = m.createTask("mc_LaunchSequence", invalid, m.onLaunchSequenceResult)
    end function

    private function onLaunchSequenceResult(result as mc.Result)
      if result.isOK
        m.log.info("launch sequence is complete - showing main screen")
        mioc.setInstance("appArgs", m.args)
        m.showInitialScreen()
      else
        m.log.error("app failed to start")
      end if
    end function

    private function showInitialScreen()
      m.log.info("show initial screen")
      m.developerScreen = mc.createSGNode("DeveloperScreen", m.top, "developerScreen")
      if m.developerScreen <> invalid
        m.log.warn("Launching in dev mode!")
        m.observeNodeField(m.developerScreen, "state", m.onDeveloperScreenState)
        m.loadingIndicator.isActive = false
        m.top.appendChild(m.developerScreen)
        mv.setFocus(m.developerScreen)
      else
        m.showAppController()
      end if
    end function

    private function onDeveloperScreenState(state as string)
      if state = "success"
        m.showAppController()
      end if
    end function

    private function showAppController()
      if m.developerScreen <> invalid
        m.top.removeChild(m.developerScreen)
        m.developerScreen = invalid
        m.loadingIndicator.isActive = true
      end if
      m.top._appController = createObject("roSGNode", "AppController")
      mioc.setInstance("appController", m.top._appController)
      m.top.insertChild(m.top._appController, 1)
      m.top._appController@._initialize()
      m.top._appController.opacity = 0
      if m.top._appController.isFirstLoadComplete
        m.onFirstLoadComplete()
      else
        m.observeNodeField(m.top._appController, "isFirstLoadComplete", m.onFirstLoadComplete, "none")
      end if
    end function

    private function onFirstLoadComplete()
      m.waitAFrame(m.showApp)
    end function

    private function showApp()
      m.global.addFields({ "appController": m.top._appController })
      m.loadingIndicator.isActive = false
      m.top._appController.opacity = 1
      mv.animations.utils.fadeTo(m.loadingBackgroundGroup, 0.3, 0)
      mv.animations.utils.fadeTo(m.loadingPosterGroup, 0.3, 0)
      m.waitAFrame(m.cleanUpLoadingViews, 0.5)
    end function

    private function cleanUpLoadingViews()
      m.top.removeChild(m.loadingBackground)
      m.top.removeChild(m.loadingPoster)
      mv.setFocus(m.top._appController)
    end function

  end class
end namespace
