import "pkg:/source/core/Utils.bs"
import "pkg:/source/ml/ListMixin.bs"
import "pkg:/source/ml/RowItemScroller.bs"
import "pkg:/source/ml/RowItemViewManager.bs"
import "pkg:/source/view/BaseView.bs"
import "pkg:/source/ml/cells/BaseCell.bs"
import "pkg:/source/view/Animation.bs"

@node("LongCell", "ml_BaseCell")
class LongCell extends ml.BaseCell
  private poster as roSGNodeNode
  private bgRect as roSGNodeNode
  private label as roSGNodeNode

  function new()
    super()
  end function

  protected override function createViews() as void
    m.bgRect = mc.createSGNode("mv_Rectangle", m.top, "bgRect", {
      size: [1192, 144]
      ' color: "#000000"
      visible: false
    })
    m.poster = mc.createSGNode("mv_Poster", m.top, "poster", {
      translation: [24, 16]
      loadingBitmapUri: "http://via.placeholder.com/80x80"
      failedBitmapUri: "http://via.placeholder.com/80x80"
      uri: "http://via.placeholder.com/80x80"
      loadWidth: 80
      loadHeight: 80
      size: [80, 80]
      loadDisplayMode: "zoomToFill"
    })
    m.label = mc.createSGNode("mv_Label", m.top, "label", {
      fontKey: "mediumBold,50"
      horizAlign: "left"
      vertAlign: "center"
      color: "#ffffff"
      translation: [120, 32]
      size: [984, 48]
    })
  end function

  protected override function onShowWithContent(content as roSGNodeNode)
    ' ? " ON SHOW WITH CONTENT " m.index
    m.poster.uri = content.HDGRIDPOSTERURL
    m.label.text = `${m.index} ${content.title}`
    m.label.fontKey = "medium,30"
    m.label.color = "#aaaaaa"
  end function

  protected override function onHide()
    ' ? " ON HIDE " m.index
    m.label.fontKey = "medium,30"
    m.label.color = "#aaaaaa"
  end function

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '++ delegate
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


  ' private function onScrollingChange(isScrolling as boolean, isLong as boolean)
  '   if not isScrolling
  '     m.label.visible = true
  '   end if
  ' end function

  ' private function onScrollingUpdate(startIndex as integer, currentIndex as integer)
  '   textVisible = abs(startIndex - currentIndex) < 2
  '   m.label.visible = textVisible
  ' end function


  private function onWillGainFocus(event as ml.ListEvent)
    ? "LC: onCellWillGainFocus " m.index " " event.direction
  end function

  private function onWillLoseFocus(event as ml.ListEvent)
    ? "LC: onCellWillLoseFocus " m.index " " event.direction

    m.label.fontKey = "medium,30"
    m.label.color = "#aaaaaa"

  end function

  private function onDidGainFocus(event as ml.ListEvent)
    ? "LC: onCellDidGainFocus " m.index " " event.direction

    m.setScale(1, true)
    m.label.fontKey = "mediumBold,40"
    m.label.color = "#ffffff"
  end function

  private function onDidLoseFocus(event as ml.ListEvent)
    ? "LC: onCellDidLoseFocus " m.index " " event.direction

    m.label.fontKey = "medium,30"
    m.label.color = "#aaaaaa"
    m.setScale(1, false)
  end function

  private function onGainingFocus(event as ml.ListEvent)
    ? "LC: onGainingFocus " m.index " " event.direction " " event.fraction

    m.setScale(event.fraction, true)
    if event.fraction > 0.8
      m.label.fontKey = "mediumBold,40"
      m.label.color = "#ffffff"
    end if
  end function

  private function onLosingFocus(event as ml.ListEvent)
    ? "LC: onLosingFocus " m.index " " event.direction " " event.fraction

    m.setScale(event.fraction, false)
    if event.fraction > 0.8
      m.label.fontKey = "mediumBold,30"
      m.label.color = "#aaaaaa"
    end if

  end function

  private function setScale(fraction as float, isGaining as boolean) as void
    ' if isGaining
    '   m.scale = (event.fraction + 0.3)
    ' else
    '   m.scale = (1 - event.fraction) + 0.3
    ' end if
    ' m.scale = m.scale * 0.8
    ' m.poster.width = m.posterSize[0] * m.scale
    ' m.poster.height = m.posterSize[1] * m.scale

    ' if isGaining
    '   m.poster.opacity = 0.3 + event.fraction
    ' else
    '   m.poster.opacity = 0.3 + (1 - event.fraction)
    ' end if
  end function

end class
