import "pkg:/source/core/Utils.bs"
import "pkg:/source/ml/cells/BaseCell.bs"

@node("PosterCell", "ml_BaseCell")
class PosterCell extends ml.BaseCell

  private poster

  function new()
    super()
  end function

  protected override function createViews() as void
    m.poster = mc.createSGNode("mv_Poster", m.top, "poster", {
      translation: [0, 0]
      loadingBitmapUri: "http://via.placeholder.com/307x200"
      failedBitmapUri: "http://via.placeholder.com/307x200"
      uri: "http://via.placeholder.com/307x200"
      loadWidth: [307, 200]
      loadHeight: [307, 200]
      size: [307, 200]
      loadDisplayMode: "zoomToFill"
    })
  end function

  protected override function onContentChange(content as mc.types.node)
    m.poster.uri = content.HDGRIDPOSTERURL
  end function
end class