import "pkg:/source/core/Utils.bs"
import "pkg:/source/ml/ListMixin.bs"
import "pkg:/source/ml/ItemDelegateMixin.bs"
import "pkg:/source/ml/RowItemScroller.bs"
import "pkg:/source/ml/RowItemViewManager.bs"
import "pkg:/source/ml/ItemFocusManager.bs"
import "pkg:/source/view/BaseView.bs"
import "pkg:/source/ml/cells/BaseCell.bs"
import "pkg:/source/view/Animation.bs"

@node("PosterCell", "ml_BaseCell")
class PosterCell extends ml.BaseCell

  @observer("onDebugMChange")
  public __debugM = false

  private poster

  function new()
    super()
  end function

  protected override function createViews() as void
    m.poster = mc.createSGNode("mv_Poster", m.top, "poster", {
      translation: [0, 0]
      loadingBitmapUri: "http://via.placeholder.com/307x200"
      failedBitmapUri: "http://via.placeholder.com/307x200"
      uri: "http://via.placeholder.com/307x200"
      loadWidth: [307, 200]
      loadHeight: [307, 200]
      size: [307, 200]
      loadDisplayMode: "zoomToFill"
    })
  end function

  protected override function onContentChange(content as mc.types.node)
    m.poster.uri = content.HDGRIDPOSTERURL
  end function
end class