import "pkg:/source/roku_modules/log/LogMixin.brs"
import "pkg:/source/core/Result.bs"

namespace sample
  @task("WaitTask", "Task")
  class WaitTask
    private log = new log.Logger("RequestTask")

    function new()
    end function

    private function execute(args as roAssociativeArray) as dynamic
      m.log.info("waiting", args.delay, "before returning", args.isOk)
      port = CreateObject("roMessagePort")
      wait(args.delay * 1000, port)

      return new mc.Result(args.isOK)
    end function

  end class
end namespace
