import "pkg:/source/ml/ListMixin.bs"
import "pkg:/source/view/BaseScreen.bs"
import "pkg:/source/ml/ListDelegateMixin.bs"
import "pkg:/source/core/DebugTimer.bs"

@node("ListScreen", "mv_BaseScreen")
class ListScreen extends mv.BaseScreen

  @observer("onRemoveItems")
  @alwaysnotify
  public removeItems = 0

  'views
  private list
  private listHolder
  private bgRect
  private button

  'style
  private numberOfRows = 20
  private defaultCellType = "ml_SimpleCell"

  'state
  public componentPool as mc.types.Node
  private contentId = 0
  private rowSettings
  private focusSettings
  private cellSettings
  private loadingIndicator
  private scrollSpeed = 2

  function new()
    super("ListScreen")
  end function

  protected override function initialize()
    super.initialize()
    translation = [0, 0]
    size = [1920, 1080]

    m.button = m.createSGNode("Button", m.top, "button", {
      title: "focus me"
    })
    m.bgRect = m.createSGNode("mv_Rectangle", m.top, "bgRect", {
      translation: translation
      size: size
      color: "#6a307d"
    })
    m.listHolder = m.createSGNode("Group", m.top, "listHolder")
    m.componentPool = m.global.componentPool

    m.list = m.createSGNode("ml_List", m.listHolder, "list", {
      translation: translation
      width: size[0]
      height: size[1]
    })
    mioc.setInstance("list", m.list)
    m.loadingIndicator = m.createSGNode("LoadingIndicator", m.top, "loadingIndicator", {
      isActive: true
      width: 1920
      height: 1080
      backgroundVisible: false
    })
    ml.delegateMixin.setListDelegate(m.list)
    m.onResetChange()
  end function

  private function onResetChange()
    m.list.content = invalid
    ' m.cellSettings = ml.listMixin.createCellSettings("ml_SimpleCell", [480, 50], 30)
    ' m.cellSettings = ml.listMixin.createCellSettings("ml_SimpleCell", [320, 250], 30)
    m.cellSettings = ml.listMixin.createCellSettings("ml_SimpleCell", [320, 130], 30)

    timer = new mc.utils.DebugTimer("list")
    m.rowSettings = ml.listMixin.createRowSettings(m.cellSettings, invalid, 30)

    m.focusSettings = ml.listMixin.createFocusSettings(m.scrollSpeed, "fixed", [-50, -50, 50, 50])
    ' listSettings = ml.listMixin.createListSettings(3000, 3000)
    listSettings = ml.listMixin.createListSettings(-1, -1)
    ' listSettings.rowCreationStrategy = "all"
    listSettings.rowCreationStrategy = "async"
    listSettings.rowCreationBatchSize = 5
    listSettings.rowCreationBatchDelay = 0.3

    ' content = ml.listMixin.createListContent(m.focusSettings, m.rowSettings, listSettings)
    ' content = ml.listMixin.createListContent(m.focusSettings, m.rowSettings, listSettings)
    ' content = ml.listMixin.createListContent(m.focusSettings, m.rowSettings, listSettings)
    content = ml.listMixin.createListContent(m.focusSettings, m.rowSettings, listSettings)
    ' content = ml.listMixin.createListContent(m.focusSettings, m.rowSettings, listSettings)

    ' items = m.createSimpleData(),
    ' items = m.createData(),
    ' items = m.createSimpleGridData(),
    ' items = m.createMockScreenData(),
    items = m.createHeaderOnlyData(),
    ' items = m.createGridData(),
    timer.log("makeData")
    m.setFocus(m.loadingIndicator)
    content@.appendChildren(items)
    m.list.visible = false
    m.list.content = content
    timer.log("set content")
    if m.list.state = "rendered"
      m.onListRenderState("rendered")
      m.loadingIndicator.isActive = false
    else
      m.observeNodeField(m.list, "state", m.onListRenderState, "value", true)
    end if
  end function

  private function onListRenderState(state as string)
    m.log.info("onListRenderState", state)
    if state = "rendered"
      m.setFocus(m.list)
      m.list@.moveToItem([0, 0], false)
      m.list.visible = true
      m.loadingIndicator.isActive = false
    end if
  end function

  private function createData()
    content = []
    rowFocusSettings = ml.listMixin.createFocusSettings(m.scrollSpeed, "fixed", [0, 0, 0, 0])
    numItems = 20
    for i = 0 to m.numberOfRows - 1
      row = createObject("roSGNode", "ml_RowContent")
      row.id = rnd(2147483647).toStr()
      if i = 0
        row0FocusSettings = ml.listMixin.createFocusSettings(m.scrollSpeed, "fixed", [0, 0, 0, 0])
        cellSettings = ml.listMixin.createCellSettings("HeroCell", [1100, 700], 30)
        row.settings = ml.listMixin.createRowSettings(cellSettings, row0FocusSettings)
        row.settings.headerSettings.position = "none"
        row.settings.contentOffset = [400, -30]
      else if i = 1 or i = 15 or i = 8
        row1FocusSettings = ml.listMixin.createFocusSettings(m.scrollSpeed, "fixed", [30, 30, -30, -30])
        ' row1FocusSettings.feedbackUri = "pkg:/images/circle.png"
        row1FocusSettings.feedbackColor = "#F4D42A"
        headerSettings = ml.listMixin.createHeaderSettings([30, 20], 80, "mediumBold,50", "#ffff00")
        cellSettings = ml.listMixin.createCellSettings("SubHeroCell", [528, 297], 100)
        row.settings = ml.listMixin.createRowSettings(cellSettings, row1FocusSettings, 30, headerSettings)
        row.settings.contentOffset = [100, 0]
        row.settings.screenPos = 400
        ' row.settings.peekNextPixels = 150
      else if i = 3 or i = 16 or i = 9
        rowFocusSettings = ml.listMixin.createFocusSettings(m.scrollSpeed, "floating", [0, 0, 0, 0])
        row.settings = ml.listMixin.createGridRowSettings(m.cellSettings, rowFocusSettings, 30, invalid, 150, 3, 330)
        row.settings.contentOffset = [100, 30]
        ' row.settings.peekNextPixels = 300
        numItems = 24
      else if i = 6 or i = 12 or i = 4 or i = 10
        row.settings = ml.listMixin.createRowSettings(m.cellSettings, rowFocusSettings)
        row.settings.contentOffset = [100, 30]
        row.settings.peekNextPixels = 0
        ' row.settings.screenPos = -1
      else if i = 5 or i = 11
        complexFocusSettings = ml.listMixin.createFocusSettings(m.scrollSpeed)
        row.settings = ml.listMixin.createCustomRowSettings("ComplexRow", 700)
        ' row.settings = ml.listMixin.createRowSettings(invalid, complexFocusSettings, 30, invalid, 0, "ComplexRow")
        ' else if i= 6
        '   row.settings = ml.listMixin.createRowSettings(m.cellSettings, rowFocusSettings)
        '   row.settings.height = 700
        '   row.settings.contentOffset = [100, -200]
        '   row.settings.peekNextPixels = 300
        ' row.settings.peekNextPixels = 150
      else
        row.settings = ml.listMixin.createRowSettings(m.cellSettings, rowFocusSettings)
        row.settings.contentOffset = [100, 30]
        ' row.settings.peekNextPixels = 300
        row.settings.screenPos = 400
        ' row.settings.peekNextPixels = 150
      end if
      ' row.settings.peekNextPixels = 200
      ' row.settings = ml.listMixin.createRowSettings(m.cellSettings, rowFocusSettings)
      ' row.settings.contentOffset = [100, 30]
      row.settings.screenPos = 400
      row.title = "ROW " + str(i)
      content.push(row)
      if i = 1
        row.settings.screenPos = 730

        ' end if
        ' if i mod 9 = 0
        '   row.addFields({ "focusType": "fixed" })
        '   ' row.addFields({ "focusType": "floatingWrap" })
        '   row.title += " fixed"
        ' else
        '   row.addFields({ "focusType": "fixed" })
        '   row.title += " fixed"
        ' end if

      else if i = 8
        row.settings.screenPos = 400
      else if i = 12 or i = 6
        ' row.settings.peekNextPixels = 0
      else if i = 13
        row.settings.screenPos = 200
        ' else if i <> 0
      end if
      'HACK
      row.settings.screenPos = -1
      ' row.settings.peekNextPixels = 0

      row@.appendChildren(m.makeItems(m.defaultCellType, numItems))
    end for
    return content
  end function

  private function createSimpleData()
    content = []
    rowFocusSettings = ml.listMixin.createFocusSettings(m.scrollSpeed, "fixed", [0, 0, 0, 0])
    for i = 0 to 20
      row = createObject("roSGNode", "ml_RowContent")
      row.id = rnd(2147483647).toStr()
      if false and i = 0
        row0FocusSettings = ml.listMixin.createFocusSettings(m.scrollSpeed, "fixed", [0, 0, 0, 0])
        cellSettings = ml.listMixin.createCellSettings("HeroCell", [1100, 700], 30)
        row.settings = ml.listMixin.createRowSettings(cellSettings, row0FocusSettings)
        row.settings.headerSettings.position = "none"
        row.settings.contentOffset = [400, -30]
        row.settings.screenPos = -1
      else
        row.settings = ml.listMixin.createRowSettings(m.cellSettings, rowFocusSettings)
        row.settings.contentOffset = [100, 30]
        ' row.settings.peekNextPixels = 300
        row.settings.screenPos = -1
      end if
      row.title = "ROW " + str(i)

      if i = 0
        row.settings.screenPos = 0
      else if i = 3
        row.settings.screenPos = 400
      else if i = 8
        row.settings.screenPos = 600
      else if i = 12
        row.settings.screenPos = 0
      else if i = 14
        row.settings.screenPos = 400
      else if i = 16
        row.settings.screenPos = 0
      else
        row.settings.screenPos = 150
      end if

      ' row.settings.screenPos = 400
      content.push(row)
      row@.appendChildren(m.makeItems(m.defaultCellType, 5))
    end for
    return content
  end function

  private function createGridData()
    content = []
    ' rowFocusSettings = ml.listMixin.createFocusSettings(m.scrollSpeed, "fixed", [0, 0, 0, 0])
    rowFocusSettings = ml.listMixin.createFocusSettings(m.scrollSpeed, "fixed", [0, 0, 0, 0])
    showHero = true

    'TODO - add normal rows around this
    ' for i = 0 to 1
    for i = 0 to 20
      row = createObject("roSGNode", "ml_RowContent")
      row.id = rnd(2147483647).toStr()
      numItems = 5
      if showHero and i = 0 or i = 10 or i = 18
        row0FocusSettings = ml.listMixin.createFocusSettings(m.scrollSpeed, "fixed", [0, 0, 0, 0])
        row0FocusSettings.feedbackStyle = "none"
        cellSettings = ml.listMixin.createCellSettings("HeroCell", [1100, 700], 30)
        row.settings = ml.listMixin.createRowSettings(cellSettings, row0FocusSettings)
        row.settings.headerSettings.position = "none"
        row.settings.contentOffset = [400, -30]
        prefix = "HERO"
        row.settings.screenPos = -1
      else if (i = 2 or i = 6 or i = 9)
        gridFocusSettings = ml.listMixin.createFocusSettings(m.scrollSpeed, "floating", [0, 0, 0, 0])
        if i = -2
          numCols = 1
        else
          numCols = 4
        end if

        row.settings = ml.listMixin.createGridRowSettings(m.cellSettings, gridFocusSettings, 30, invalid, 150, numCols, 100, 5, 50)
        row.settings.contentOffset = [100, 30]
        prefix = "GRID"
        ' row.settings.peekNextPixels = 300
        numItems = 10
      else
        focusSettings = ml.listMixin.createFocusSettings(m.scrollSpeed, "fixed", [0, 0, 0, 0])
        ' focusSettings = ml.listMixin.createFocusSettings(m.scrollSpeed, "floating", [0, 0, 0, 0])
        row.settings = ml.listMixin.createRowSettings(m.cellSettings, focusSettings)
        row.settings.contentOffset = [100, 30]
        prefix = "HORIZ"
        ' row.settings.peekNextPixels = 300
        row.settings.screenPos = -1
        if i = 1 or i = 19
          row.settings.screenPos = 800
        else if i = 5 or i = 15
          row.settings.screenPos = 600
        else if i = 3 or i = 7
          row.settings.screenPos = 200
        else or i = 13
          row.settings.screenPos = 50
        end if
        numItems = 100
      end if
      row.title = "ROW " + str(i)
      ' row.settings.screenPos = 400
      content.push(row)
      row@.appendChildren(m.makeItems(m.defaultCellType, numItems, prefix))
    end for

    return content
  end function

  private function createHeaderOnlyData()
    content = []
    rowFocusSettings = ml.listMixin.createFocusSettings(m.scrollSpeed, "fixed", [0, 0, 0, 0])

    i = 0
    row = createObject("roSGNode", "ml_RowContent")
    row.id = rnd(2147483647).toStr()
    numItems = 5
    row0FocusSettings = ml.listMixin.createFocusSettings(m.scrollSpeed, "fixed", [0, 0, 0, 0])
    row0FocusSettings.feedbackStyle = "none"
    cellSettings = ml.listMixin.createCellSettings("HeroCell", [1100, 700], 30)
    row.settings = ml.listMixin.createRowSettings(cellSettings, row0FocusSettings)
    row.settings.headerSettings.position = "none"
    row.settings.contentOffset = [400, -30]
    prefix = "HERO"
    row.settings.screenPos = -1

    row.title = "ROW " + str(i)
    ' row.settings.screenPos = 400
    content.push(row)
    row@.appendChildren(m.makeItems(m.defaultCellType, numItems, prefix))

    return content
  end function

  private function createModule(title as string)
    gridFocusSettings = ml.listMixin.createFocusSettings(m.scrollSpeed, "floating", [0, 0, 0, 0])
    numCols = 4
    prefix = "G "
    row = createObject("roSGNode", "ml_RowContent")
    row.id = rnd(2147483647).toStr()
    row.settings = ml.listMixin.createGridRowSettings(m.cellSettings, gridFocusSettings, 30, invalid, 150, numCols, 100, 5, 50)
    row.settings.contentOffset = [100, 30]
    numItems = 10
    row.title = title
    row@.appendChildren(m.makeItems(m.defaultCellType, numItems, prefix))
    return row
  end function


  private function createSimpleGridData()
    content = []
    rowFocusSettings = ml.listMixin.createFocusSettings(m.scrollSpeed, "fixed", [0, 0, -10, -140])
    showHero = false
    showGrid = false

    'TODO - add normal rows around this
    for i = 0 to 30
      row = createObject("roSGNode", "ml_RowContent")
      row.id = rnd(2147483647).toStr()
      numItems = 20
      if showHero and i = 0
        row0FocusSettings = ml.listMixin.createFocusSettings(m.scrollSpeed, "fixed", [0, 0, 0, 0], "none")
        cellSettings = ml.listMixin.createCellSettings("HeroCell", [1100, 400], 30)
        row.settings = ml.listMixin.createRowSettings(cellSettings, row0FocusSettings)
        row.settings.headerSettings.position = "none"
        row.settings.contentOffset = [400, -30]
      else if i = 4 and showGrid
        gridFocusSettings = ml.listMixin.createFocusSettings(m.scrollSpeed, "fixed", [-10, -10, 20, -110])
        row.settings = ml.listMixin.createGridRowSettings(m.cellSettings, gridFocusSettings, 30, invalid, 400, 3, 427, 2, 100)
        row.settings.contentOffset = [100, 30]
        numItems = 14
      else if i = 2 and showGrid
        gridFocusSettings = ml.listMixin.createFocusSettings(m.scrollSpeed, "fixed", [-10, -10, 10, -120], "underneath")
        gridFocusSettings.feedbackUri = "pkg:/images/solid.9.png"
        gridFocusSettings.feedbackColor = "#F7F700"

        row.settings = ml.listMixin.createGridRowSettings(m.cellSettings, gridFocusSettings, 30, invalid, 400, 3, 427)
        row.settings.contentOffset = [100, 30]
        numItems = 14
      else
        row.settings = ml.listMixin.createRowSettings(m.cellSettings, rowFocusSettings)
        row.settings.contentOffset = [100, 30]
      end if
      row.title = "ROW " + str(i)
      if i = 1
        row.settings.screenPos = 700
      else if i = 5
        row.settings.screenPos = 500
      end if
      content.push(row)
      row@.appendChildren(m.makeItems(m.defaultCellType, numItems))
    end for
    return content
  end function

  private function createMockScreenData()
    content = []
    rowFocusSettings = ml.listMixin.createFocusSettings(m.scrollSpeed, "fixed", [0, 0, 0, 0])
    showHero = true
    headerSettings = ml.listMixin.createHeaderSettings([30, 20], 100, "mediumBold,50", "#ffff00")
    row = createObject("roSGNode", "ml_RowContent")
    row.title = "FAVORITE"
    row.id = rnd(2147483647).toStr()
    cellSettings = ml.listMixin.createCellSettings("PosterCell", [307, 200], 30)
    row.settings = ml.listMixin.createRowSettings(cellSettings, rowFocusSettings, 30, headerSettings)
    row.settings.contentOffset = [200, 0]
    numItems = 1
    row.settings.screenPos = 400
    content.push(row)
    row@.appendChildren(m.makeItems(m.defaultCellType, numItems))

    row = createObject("roSGNode", "ml_RowContent")
    row.title = "FOLLOWING"
    row.id = rnd(2147483647).toStr()
    cellSettings = ml.listMixin.createCellSettings("PosterCell", [307, 200], 40)
    row.settings = ml.listMixin.createRowSettings(cellSettings, rowFocusSettings, 30, headerSettings, 330)
    row.settings.contentOffset = [200, 0]
    numItems = 20
    content.push(row)
    row@.appendChildren(m.makeItems(m.defaultCellType, numItems))

    row = createObject("roSGNode", "ml_RowContent")
    row.title = "TEAMS"
    row.id = rnd(2147483647).toStr()
    cellSettings = ml.listMixin.createCellSettings("LongCell", [1192, 144], 40)
    gridFocusSettings = ml.listMixin.createFocusSettings(m.scrollSpeed, "fixed", [0, 0, 0, 0])
    row.settings = ml.listMixin.createGridRowSettings(cellSettings, gridFocusSettings, 30, headerSettings, 400, 1, 144, 4, 100)
    ' row.settings = ml.listMixin.createGridRowSettings(cellSettings, gridFocusSettings, 30, headerSettings, 400, 1, 144, 2, -1)
    ' row.settings = ml.listMixin.createGridRowSettings(cellSettings, gridFocusSettings, 30, headerSettings, 0, 1, 144, 5, -1)
    ' row.settings = ml.listMixin.createGridRowSettings(cellSettings, gridFocusSettings, 30, headerSettings, 0, 1, 144, 4, -1)
    row.settings.contentOffset = [200, 30]
    numItems = 12
    row.settings.screenPos = 400
    content.push(row)
    row@.appendChildren(m.makeItems(m.defaultCellType, numItems))
  end for
  return content
end function

private function addItems(cellType as string, number as integer)
  row = m.list.content.getChild(m.list.focusedRowIndex)
  row@.appendChildren(m.makeItems(cellType, number))
end function

private function makeItems(cellType as string, number as integer, prefix = "Item" as string)
  items = []
  for i = 0 to number - 1
    items.push(m.makeItem(cellType, `${prefix} ${m.contentId} [${i}]`))
  end for
  return items
end function

private function makeItem(cellType as string, title as string) as mc.types.node
  child = createObject("roSGNode", "ContentNode")
  id = str(m.contentId).trim()
  child.id = rnd(2147483647).toStr()
  child.description = "some really long " + id + "text in here " + id
  child.HDGRIDPOSTERURL = "https://picsum.photos/id/" + str(m.contentId mod 1000).trim() + "/340/340"
  child.title = title
  m.contentId++
  return child
end function

private function onRemoveItems(numItems as integer)
  row = m.list.content.getChild(m.list.focusedRowIndex)
  startIndex = row.getChildCount() - items
  row@.removeChildrenIndex(startIndex, numItems)
end function

private function addRow(index as integer)
  ? ">>>ADD ROW"
  ? ">>>ADD ROW"
  ? ">>>ADD ROW"
  ? ">>>ADD ROW"
  rowFocusSettings = ml.listMixin.createFocusSettings(m.scrollSpeed, "fixed", [0, 0, 0, 0])
  row = createObject("roSGNode", "ml_RowContent")
  rowFocusSettings.feedbackColor = "#F4D42A"
  headerSettings = ml.listMixin.createHeaderSettings([30, 20], 80, "mediumBold,50", "#ffff00")
  cellSettings = ml.listMixin.createCellSettings("ml_SimpleCell", [320, 200], 100)
  row.settings = ml.listMixin.createRowSettings(cellSettings, rowFocusSettings, 30, headerSettings)
  row.settings.contentOffset = [100, 0]

  row.title = "NEW ROW " + m.contentId.toStr()
  row.id = rnd(2147483647).toStr()
  m.contentId++
  row@.appendChildren(m.makeItems(m.defaultCellType, 5))
  m.list.content@.insertChild(row, index)
end function

private function removeRow(index as integer)
  m.list.content@.removeChildIndex(index)
end function

private function addCell()
  rowContent = m.list.content.getChild(m.list.focusedRowIndex)
  rowContent@.appendChildren(m.makeItems(m.defaultCellType, 1))
  rowContent@.insertChild(m.makeItems(m.defaultCellType, 1), m.list.focusedCellIndex)
end function

private function removeCell()
  rowContent = m.list.content.getChild(m.list.focusedRowIndex)
  ? "REMOVING CHILD AT "; m.list.focusedCellIndex
  rowContent@.removeChildIndex(m.list.focusedCellIndex)
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ keypresses
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
private firstItem = invalid
private dataIndex = 0
private function onKeyPressOptions() as boolean
  ? "OPTIONS "

  m.dataIndex = mc.clamp(m.dataIndex + 1, 0, 7)

  m.mergeLoadedData()
  ' if m.firstItem = invalid
  '   m.firstItem = m.list.content.getChild(0)
  '   m.list.content.removeChild(m.firstItem)
  ' else
  '   m.list.content.insertChild(m.firstItem, 0)
  '   m.firstItem = invalid
  ' end if

  ' m.firstItem = m.list.content.getChild(0)
  ' m.firstItem.isHidden = not m.firstItem.isHidden
  ' row.isHidden = not row.isHidden
  ' m.list.content = invalid
  ' m.onResetChange()
  return true
end function

private function mergeLoadedData()
  m.removeNonHeaderRows(false)
  newModules = []
  modules = []
  numModules = 0
  if m.dataIndex = 1
    modules.push(m.createModule("LIVE"))
  end if
  if m.dataIndex = 2 or m.dataIndex = 4 or m.dataIndex = 6
    modules.push(m.createModule("UPCOMING"))
  end if
  if m.dataIndex = 3 or m.dataIndex = 5 or m.dataIndex = 7
    modules.push(m.createModule("FINAL"))
  end if
  'ensure that row offsets are applied correctly
  for each module in modules
    if module.getChildCount() > 0
      if numModules > 0 and module.settings.subType() = "ml_GridRowSettings"
        settings = module.settings.clone(true)
        settings.firstRowScreenPos = settings.otherRowScreenPos
        module.settings = settings
      end if
      newModules.push(module)
      numModules++
    end if
  end for

  m.header.isShowingNoGamesMessage = numModules = 0

  m.list.content@.insertChildren(newModules, 1)
  m.list.content@.notifyUpdate()
end function

private function removeNonHeaderRows(update = true as boolean)
  rows = m.list.content.getChildren(-1, 0)
  m.list.content@.setNotificationsEnabled(false)
  for i = rows.count() - 1 to 0 step -1
    rowContent = rows[i]
    if rowContent.title = "LIVE" or rowContent.title = "UPCOMING" or rowContent.title = "FINAL"
      m.list.content@.removeChildIndex(i)
    end if
  end for

  if update
    m.list.content@.notifyUpdate()
  end if
end function


private function onKeyPressRewind() as boolean
  ? "REMOVING "
  m.removeCell()
  return true
end function

private function onKeyPressFastForward() as boolean
  ? "ADDING"
  ' m.addRow(1)
  m.addCell()
  return true
end function

private function onKeyPressBack() as boolean
  if m.top.isRoot <> true
    m.list.isHidden = true
    m.pop()
  end if
  return true
end function

private function onKeyPressUp() as boolean
  ? "FOCUS ON BUTTON"
  m.setFocus(m.button)
  return true
end function

private function onKeyPressDown() as boolean
  '    ? "FOCUS ON LIST"
  m.setFocus(m.list)
  return true
end function

private function onKeyPressBack() as boolean
  ? "FOCUS ON BUTTON"
  if not m.button.isSameNode(m.focusedControl)
    m.setFocus(m.button)
    return true
  end if
  ? " EXIT"
  return false
end function


'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ lifecycle
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

protected override function onShow()
  super.onShow()
  m.list.isHidden = false
  m.setFocus(m.list)
end function

protected override function onHide()
  super.onHide()
  m.list.isHidden = true
end function

protected override function onGainedFocus(isSelfFocused as boolean)
  super.onGainedFocus(isSelfFocused)
  m.log.info("onGainedFocus", isSelfFocused)

  if isSelfFocused
    m.setFocus(m.list)
  end if
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ list delegate
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

private function onCellWillGainFocus(rowIndex as integer, itemIndex as integer, direction as integer)
  ' ? "+SCREEN onCellWillGainFocus : R: "; rowIndex ; " I: " ; itemIndex; " D:" ; direction
  mioc.setInstance("focusedIndex", {
    row: rowIndex
    cell: itemIndex
  })
end function

private function onCellDidGainFocus(rowIndex as integer, itemIndex as integer, direction as integer)
  ' ? "+SCREEN onCellDidGainFocus  : R: "; rowIndex ; " I: " ; itemIndex; " D:" ; direction
  mioc.setInstance("focusedIndex", {
    row: rowIndex
    cell: itemIndex
  })
end function


private function onCellDidLoseFocus(rowIndex as integer, itemIndex as integer, direction as integer)
  ' ? "+SCREEN onCellDidLoseFocus : R: "; rowIndex ; " I: " ; itemIndex; " D:" ; direction
end function

private function onRowDidGainFocus(rowIndex as integer, direction as integer)
  ' ? "+SCREEN onRowDidGainFocus : R: "; rowIndex ; " D:" ; direction

  row = m.list@.getRowRenderer(rowIndex)
  if row <> invalid
    mioc.setInstance("focusedIndex", {
      row: rowIndex
      cell: row.focusedCellIndex
    })
  else
    mioc.setInstance("focusedIndex", {
      row: -1
      cell: -1
    })

  end if

  ' if direction = -1
  '   row = m.list@.getRowRenderer(rowIndex)
  '   row.opacity = 1
  ' end if
end function

private function onRowDidLoseFocus(rowIndex as integer, direction as integer)
  ' ? "+SCREEN onRowDidLoseFocus : R: "; rowIndex ; " D:" ; direction

  ' row = m.list@.getRowRenderer(rowIndex)
  ' if direction = 1
  '   row.opacity = 0
  ' end if

end function

private function onRowGainingFocus(rowIndex as integer, direction as integer, fraction as float)
  ' ? "+SCREEN onRowGainingFocus : R: "; rowIndex ; " D:" ; direction ; " F: " ; fraction
  ' if direction = -1
  '   row = m.list@.getRowRenderer(rowIndex)
  '   row.opacity = fraction
  ' end if
end function

private function onRowLosingFocus(rowIndex as integer, direction as integer, fraction as float)
  ' ? "+ onRowLosingFocus : R: "; rowIndex ; " D:" ; direction ; " F: " ; fraction
  ' if direction = 1
  '   row = m.list@.getRowRenderer(rowIndex)
  '   row.opacity = 1 - fraction
  ' end if

end function
private function onCellGainingFocus(rowIndex as integer, cellIndex as integer, direction as integer, fraction as float)
  ' ? "+SCREEN onCellGainingFocus : R: "; rowIndex ; " C " ; cellIndex; " D:" ; direction ; " F: " ; fraction
  ' if direction = -1
  '   row = m.list@.getRowRenderer(rowIndex)
  '   row.opacity = fraction
  ' end if
end function

private function onCellLosingFocus(rowIndex as integer, cellIndex as integer, direction as integer, fraction as float)
  ' ? "+ onRowLosingFocus : R: "; rowIndex ; " D:" ; " C " ; cellIndex; direction ; " F: " ; fraction
  ' if direction = 1
  '   row = m.list@.getRowRenderer(rowIndex)
  '   row.opacity = 1 - fraction
  ' end if

end function

private function onItemSelected(rowIndex as integer, itemIndex as integer)
  ? ">>>onItemSelected changed to:" ; rowIndex ; "," ; itemIndex
  ? ">>>onItemSelected changed to:" ; rowIndex ; "," ; itemIndex
  ? ">>>onItemSelected changed to:" ; rowIndex ; "," ; itemIndex
  rowContent = m.list.content.getChild(rowIndex)
  title = `NEW Item ${m.contentId}`
  child = m.makeItem("SimpleCell", title)
  rowContent.insertChild(child, itemIndex)
  ' rowContent.removeChild(child)
  row = m.list@.getRowRenderer(rowIndex)
  row@.forceUpdate()
  ' newScreen = createObject("roSGNode", "ListScreen")
  ' m.push(newScreen)
  ' m.setFocus(newScreen)
end function

end class
