import "pkg:/source/view/BaseCell.bs"
import "pkg:/source/core/Utils.bs"
import "pkg:/source/core/IOC.bs"

namespace cells
  @strict
  @node("RowListCell", "BaseCell")
  class RowListCell extends view.cells.BaseCell
    public trackingId = ""

    'view elements
    private poster
    private label
    private bgRect
    private rectangle
    private posterSize = [480.0, 320.0]
    private lastContent = invalid
    function new()
      super()
    end function

    protected override function onContentChange(content as types.node)
      if content = invalid or content.isSameNode(m.lastContent)
        m.global.cellTracker@.unbindCell(m.top)
      end if
      m.global.cellTracker@.bindCellToContent(m.top, content)

      super.onContentChange(content)
      m.poster.uri = content.HDGRIDPOSTERURL
      m.label.text = content.title
    end function

    protected override function _createView() as void
      super._createView()
      ' scaleRotateCenter: [0, m.posterSize[1]]
      m.bgRect = createSGNode("Rectangle", m.top, "bgRect", {
        size: m.posterSize
        color: "#2222aa"
      })
      m.poster = createSGNode("Poster", m.top, "poster", {
        translation: [0, 0]
        scaleRotateCenter: [0, 0]
        loadingBitmapUri: "http://via.placeholder.com/370x300"
        failedBitmapUri: "http://via.placeholder.com/370x300"
        uri: "http://via.placeholder.com/370x300"
        loadWidth: m.posterSize[0]
        loadHeight: m.posterSize[1]
        size: m.posterSize
        loadDisplayMode: "scaleToFit"
      })
      m.rectangle = createSGNode("Rectangle", m.top, "rectangle", {
        opacity: 0.4
        color: "#000000"
        width: m.posterSize[0]
        height: 20
      })
      m.label = createSGNode("Label", m.top, "label", {
        width: m.posterSize[0]
        horizAlign: "center"
        translation: [10, 10]
      })
      m.label = m.top.findNode("label")
    end function

  end class
end namespace