import "pkg:/source/view/BaseScreen.bs"

namespace screens
  class BaseAppController extends mv.BaseScreen

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    '++ Initialization
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    function new()
      super(m.__className)
    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    '++ Public Methods
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    function onExecuteSelection(selection as mc.types.node)
      'override this method and supply the require logic
      return true
    end function

  end class
end namespace