import "pkg:/source/view/BaseScreen.bs"

namespace mv
  class BaseAppController extends mv.BaseScreen

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    '++ Public Fields
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    isDestroyable = false

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    '++ Initialization
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    function new(name as string)
      super(name)
    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    '++ Public Methods
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    ' returns {boolen} - true if the selection was completed synchronously
    function onExecuteSelection(selection as mc.types.node) as boolean
      m.setInstance("currentSelection", selection)
      return true
    end function

  end class
end namespace
