namespace tests.utils
  function configureViewManager(viewManager, axes, numItems = 20, itemSize = [300, 300], screenSize = [1920, 1080])
    owner = viewManager.owner
    container = viewManager.container

    owner.translation = [0, 0]
    owner.width = screenSize[0]
    owner.height = screenSize[1]

    container.translation = [0, 0]
    container.width = screenSize[0]
    container.height = screenSize[0]

    children = []

    for i = 0 to numItems
      children.push({
        id: str(i).trim()
      })
    end for
    content = new rooibos.utils.MockNode("listContent")
    content.children = children
    content.focusSettings = ml.listMixin.createFocusSettings()
    content.rowSettings = ml.listMixin.createRowSettings()

    viewManager.itemSize = itemSize
    viewManager.setContent(content)
  end function

end namespace
