function init()
  m.top.observeFieldScoped("style", "onStyleChange")
  m.top.observeFieldScoped("size", "onSizeChange")
end function

function onStyleChange()
  m.top.setFields(m.top.style)
  'hardcoded due to layout bugs
  m.top.height = 550
  m.top.width = 1300
end function

function onSizeChange()
  if m.top.size <> invalid and m.top.size.count() > 0
    m.top.width = m.top.size[0]
    m.top.height = m.top.size[1]
  end if
end function

