import "pkg:/source/core/Utils.bs"

namespace models
  @node("Item", "ContentNode")
  class Item

    public json as roAssociativeArray

    public version = 0
    public type = ""
    public isSerializable = true

    public function toString() as string
      return "<Item> (" + m.top.id + ") - '" + mc.getPath(m.json, "title", "NO TITLE") + "'"
    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    '++ Serialization support
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    public function serialize() as roAssociativeArray
      return {
        type: m.type
        json: m.json
      }
    end function

    public function deserialize(data as roAssociativeArray)
      m.json = data.json
      m.type = data.type
    end function

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    '++ Cloning
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    protected function cloneCustomFieldsIntoNode(node as roSGNodeNode)
      node.isSerializable = true
      node.type = m.top.type
    end function

  end class
end namespace
