import "pkg:/source/ml/ListMixin.bs"
import "pkg:/source/view/BaseScreen.bs"
import "pkg:/source/core/Utils.bs"

@node("FocusTestScreen", "mv_BaseScreen")
class FocusTestScreen extends mv.BaseScreen

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '++ Views
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  private mainGroup as roSGNodeNode
  private group1 as roSGNodeNode
  private button1 as roSGNodeNode
  private button2 as roSGNodeNode
  private group2 as roSGNodeNode
  private button3 as roSGNodeNode
  private button4 as roSGNodeNode
  private focusTrap as roSGNodeNode

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '++ Private Fields
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


  private isFocusLocked = false

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '++ Initialization
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  function new()
    super("FocusTestScreen")
  end function

  protected override function initialize()
    super.initialize()

    bundle = m.styleManager@.loadBundle("pkg:/source/debug-screens/FocusTestScreen.json")
    m.createViewsFromStyleJson(bundle.views)
    m.mainGroup@.updateChildren()
    m.observe(m.mainGroup.focusedIndex, function(index as integer)
      ? " FOCUSED INDEX NOW " index " new control " mc.dv(m.mainGroup@.getFocusedControl())
      m.setFocus(m.mainGroup@.getFocusedControl())
    end function)

    m.observe(m.button1.selected, function()
      ? "LOCKING FOCUS ON GROUP 2"
      m.setFocusLocked(m.group2, "locking on group 2")
    end function, "none")

    m.observe(m.focusTrap.selected, function()
      ? "SETTING FOCUS ON GROUP1"
      m.setFocus(m.mainGroup)
    end function, "none")

    m.group1@.updateChildren()
    m.group2@.updateChildren()
    m.focusedControl = m.mainGroup
  end function

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '++ Key Presses
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  private function isCapturingAnyKeyPress(key as string, press as boolean) as boolean
    return key <> "back"
  end function

  private function onKeyPressPlay() as boolean
    ? "UNLOCKING FOCUS"
    m.setFocusUnlocked()
    return true
  end function

  private function onKeyPressRewind() as boolean
    m.setFocus(m.focusTrap)
    return true
  end function

  private function onKeyPressOptions() as boolean
    ? " SETTING FOCUS ON BUTTON 4"
    m.setFocus(m.mainGroup)
    m.mainGroup@.setFocusedControl(m.group2)
    m.group2@.setFocusedControl(m.button4)
    return true
  end function
end class
