import "pkg:/source/tests/BaseTestSuite.spec.bs"
import "pkg:/source/core/DestroyUtils.bs"


namespace tests
  @only
  @suite("DestroyUtils tests")
  class DestroyUtilTests extends tests.BaseTestSuite

    private screen

    protected override function beforeEach()
      super.beforeEach()
    end function

    'TODO - update to rooibos 5.8.0 and use new namespace method mocking
  end class
end namespace
