import "pkg:/source/view/BaseView.bs"
import "pkg:/source/game/GameEnums.bs"

namespace mg
  @observersWaitInitialize
  @node("Collectable", "mv_Poster")
  class Collectable extends mv.BaseView

    startIndex as integer
    length as integer
    rowIndex as integer
    isCollected as boolean

    function new()
      super("Player")
      m.top.uri = "pkg:/images/sprites/coin-tile.png"
    end function

    protected override function initialize()
      super.initialize()
    end function

    function getCollision(target as mc.types.node) as object
      translation = m.top.translation
      size = m.top.size
      size[1] = 20 'only first 20 pixels of floor count
      targetSize = [target.width, target.height]
      targetTranslation = target.translation
      parentTranslation = target.getParent().translation

      ' Calculate the absolute position of the target in the scene
      collisionTranslation = [
        targetTranslation[0] + parentTranslation[0],
        targetTranslation[1] + parentTranslation[1]
      ]

      ' Check for horizontal overlap
      horizontalOverlap = (translation[0] < collisionTranslation[0] + targetSize[0]) and (translation[0] + size[0] > collisionTranslation[0])

      ' Check for vertical overlap considering the size of both the player and the target
      verticalOverlap = (translation[1] < collisionTranslation[1] + targetSize[1]) and (translation[1] + size[1] > collisionTranslation[1])

      if horizontalOverlap and verticalOverlap
        return mg.Collision.Inside
      end if

      return mg.Collision.None
    end function

  end class

end namespace
