namespace mg
  enum PlatformCollision
    UnderPlatform = "UnderPlatform"
    InPlatform = "InPlatform"
    OnPlatform = "OnPlatform"
    None = "None"
  end enum

  enum Collision
    Inside = "Inside"
    None = "None"
  end enum

  enum GameItemType
    None = "none"
    SpawnPoint = "SpawnPoint"
    Coin = "coin"
    Enemy1 = "Enemy1"
    Enemy2 = "Enemy2"
    Spikes = "Spikes"
  end enum

  enum GameItemEffect
    None = "none"
    Coin = "coin"
    Kill = "kill"
  end enum
end namespace
