import "pkg:/source/core/MIOC.bs"
import "pkg:/source/roku_modules/log/LogMixin.brs"
namespace tests

  @strict
  class BaseTestSuite extends rooibos.BaseTestSuite
    private log

    override function setup()
      tests.setUpMScope()
      m.log = new log.Logger(m.name)
    end function

    override function beforeEach()
    end function

    override function afterEach()
    end function
  end class

  function setUpMScope()
    log.initializeLogManager()
    m.log = new log.Logger("rooibosScope")
  end function
end namespace