import "pkg:/source/core/MIOC.bs"
import "pkg:/source/roku_modules/log/LogMixin.brs"
import "pkg:/source/tests/BaseTestSuite.spec.bs"

namespace mv.tests

  @strict
  class BaseTestSuite extends tests.BaseTestSuite
    private styleManager

    protected override function beforeEach()
      mioc.createContainer()
      'bs:disable-next-line
      m.styleManager = createObject("roSGNode", "mv_StyleManager")
      mioc.setInstance("styleManager", m.styleManager)
    end function

    protected override function afterEach()
      mioc.reset()
      mioc.clearClassInstances()
    end function
  end class

  function setUpMScope()
    log.initializeLogManager()
    m.log = new log.Logger("rooibosScope")
  end function
end namespace