import "pkg:/source/core/IOC.bs"
import "pkg:/source/roku_modules/log/LogMixin.brs"
namespace tests

  @strict
  class BaseTestSuite extends rooibos.BaseTestSuite
    private styleManager
    private log

    protected override function setup()
      tests.setUpMScope()
      m.log = new log.Logger(m.name)
    end function

    protected override function beforeEach()
      ioc.createContainer()
      m.styleManager = createObject("roSGNode", "StyleManager")
      ioc.setInstance("styleManager", m.styleManager)
    end function

    protected override function afterEach()
      ioc.reset()
      ioc.clearClassInstances()
    end function
  end class

  function setUpMScope()
    log.initializeLogManager()
    m.log = new log.Logger("rooibosScope")
  end function
end namespace